[project]
name = "aec-hack-gscan"
version = "0.1.0"
description = "Python server for generating slices of voxel data."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "neuroglancer>=2.40.1",
]
